# Config for https://github.com/release-drafter/release-drafter
name-template: 'v$RESOLVED_VERSION-buildpackless'
tag-template: 'v$RESOLVED_VERSION-buildpackless'
filter-by-commitish: true
commitish: buildpackless

change-template: '- $TITLE [#$NUMBER] by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Full Changelog

  Following pull requests got merged for this release:

  $CHANGES

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
