name: Test Builder

on:
  workflow_dispatch: {}

jobs:

  smoke:
    name: Smoke Test
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Smoke Tests
      run: ./scripts/smoke.sh
