name: Update buildpackless builder.toml and Send Pull Request

on:
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch: {}

jobs:
  update:
    name: Update builder.toml
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        ref: buildpackless


    - name: Checkout branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: "automation/bpless-builder-toml"

    - name: Update builder.toml
      uses: paketo-buildpacks/github-config/actions/builder/update@main

    - name: Git commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Update buildpackless builder.toml"
        pathspec: "builder.toml"
        keyid: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY_ID }}
        key: ${{ secrets.PAKETO_BOT_GPG_SIGNING_KEY }}

    - name: Git push
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: "automation/bpless-builder-toml"

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        title: "Updating buildpackless builder.toml"
        branch: "automation/buildpackless-builder-toml"
        base: "buildpackless"
